/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 --shadows public/chair.glb --output src/models/chair.jsx 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/chair.glb')
  return (
    <group {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes.Cube.geometry} material={materials['Material.002']} position={[-1.269, 0.087, 1.073]} rotation={[0, 0, -0.16]} />
      <mesh castShadow receiveShadow geometry={nodes.seat.geometry} material={materials['Material.003']} position={[-0.009, 2.213, 0.288]} />
      <mesh castShadow receiveShadow geometry={nodes.Seat_Back.geometry} material={materials['Material.004']} position={[0, 3.461, -1.116]} rotation={[1.337, 0, 0]} />
      <mesh castShadow receiveShadow geometry={nodes.Cube001.geometry} material={materials.Material} position={[0, 1.529, 0.932]} rotation={[-0.104, 0, 0]} />
      <mesh castShadow receiveShadow geometry={nodes.Cube002.geometry} material={materials['Material.001']} position={[0, 1.496, -0.937]} rotation={[0.075, 0, 0]} />
      <mesh castShadow receiveShadow geometry={nodes.Screw_Fastener.geometry} material={materials['Material.005']} position={[-0.912, 2.317, -0.287]} rotation={[-0.056, 0.005, -0.183]} />
      <mesh castShadow receiveShadow geometry={nodes.Screw_Fastener001.geometry} material={materials['Material.008']} position={[-0.891, 2.38, 0.762]} rotation={[-0.062, 0.006, -0.195]} />
      <mesh castShadow receiveShadow geometry={nodes.Screw_Fastener002.geometry} material={materials['Material.005']} position={[-0.803, 3.1, -0.785]} rotation={[1.374, 0.05, -0.459]} />
      <mesh castShadow receiveShadow geometry={nodes.Screw_Fastener003.geometry} material={materials['Material.006']} position={[-0.697, 3.692, -0.975]} rotation={[1.358, 0.058, -0.386]} />
    </group>
  )
}

useGLTF.preload('/chair.glb')
