/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/globe.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/globe.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[-0.133, 1.78, -0.923]} rotation={[-0.49, -0.012, 0.046]} scale={[0.521, 0.115, 0.435]}>
        <mesh geometry={nodes.Cube.geometry} material={materials.darkwood} />
        <mesh geometry={nodes.Cube_1.geometry} material={materials.lightwood} />
      </group>
      <mesh geometry={nodes.water.geometry} material={materials['Material.004']} scale={2.021} />
      <mesh geometry={nodes.cloud_ref001.geometry} material={materials['Material.022']} position={[-0.318, 0.408, 1.947]} rotation={[-1.787, 0.696, 3.019]} scale={[0.165, 0.204, 0.128]} />
      <mesh geometry={nodes.cloud_ref003.geometry} material={materials['Material.022']} position={[0.388, 0.722, 1.841]} rotation={[2.478, 1.271, -1.227]} scale={[0.165, 0.204, 0.128]} />
      <mesh geometry={nodes.cloud_ref005.geometry} material={materials['Material.022']} position={[-1.634, -0.425, 1.104]} rotation={[-0.944, 0.164, 2.293]} scale={[0.165, 0.204, 0.128]} />
      <mesh geometry={nodes.cloud_ref006.geometry} material={materials['Material.022']} position={[-1.73, -0.93, 0.411]} rotation={[-1.222, -0.396, 1.984]} scale={[0.165, 0.204, 0.128]} />
      <mesh geometry={nodes.cloud_ref004.geometry} material={materials['Material.022']} position={[-1.032, 0.259, 1.7]} scale={[0.165, 0.204, 0.128]} />
      <group position={[0.151, 2.104, 0.383]} rotation={[0.142, -0.221, -0.101]} scale={[27.744, 14.647, 23.707]}>
        <mesh geometry={nodes.Cube014.geometry} material={materials['Material.011']} />
        <mesh geometry={nodes.Cube014_1.geometry} material={materials['Material.008']} />
        <mesh geometry={nodes.Cube014_2.geometry} material={materials['Material.013']} />
        <mesh geometry={nodes.Cube014_3.geometry} material={materials['Material.011']} />
        <mesh geometry={nodes.Cube014_4.geometry} material={materials['Material.015']} />
      </group>
      <group position={[-0.902, -1.514, 1.219]} rotation={[1.469, 1.053, 1.015]} scale={[1, 1, 0.133]}>
        <mesh geometry={nodes.Cube019.geometry} material={materials['Material.007']} />
        <mesh geometry={nodes.Cube019_1.geometry} material={materials['Material.006']} />
      </group>
      <group position={[-1.905, -0.243, -0.568]} rotation={[-0.308, -0.31, 1.576]} scale={8.133}>
        <mesh geometry={nodes.Cube005.geometry} material={materials['Material.016']} />
        <mesh geometry={nodes.Cube005_1.geometry} material={materials['Material.020']} />
        <mesh geometry={nodes.Cube005_2.geometry} material={materials['Material.015']} />
        <mesh geometry={nodes.Cube005_3.geometry} material={materials['Material.017']} />
        <mesh geometry={nodes.Cube005_4.geometry} material={materials['Material.018']} />
      </group>
      <group position={[1.455, 1.238, -0.627]} rotation={[-0.378, 0.153, -0.763]} scale={8.133}>
        <mesh geometry={nodes.Cube005.geometry} material={materials['Material.016']} />
        <mesh geometry={nodes.Cube005_1.geometry} material={materials['Material.020']} />
        <mesh geometry={nodes.Cube005_2.geometry} material={materials['Material.015']} />
        <mesh geometry={nodes.Cube005_3.geometry} material={materials['Material.017']} />
        <mesh geometry={nodes.Cube005_4.geometry} material={materials['Material.018']} />
      </group>
      <mesh geometry={nodes.Icosphere004.geometry} material={materials.dirt} />
      <mesh geometry={nodes.Icosphere004_1.geometry} material={materials.grass} />
      <mesh geometry={nodes.Icosphere004_2.geometry} material={materials.green} />
    </group>
  )
}

useGLTF.preload('/globe.glb')
